services:

  backend:
    build: ./backend
    container_name: ai-resume-backend
    ports:
      - "8000:8000"
    environment:
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: ai-resume-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend